// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: type=lint
// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `com.demo.demo.DemoPlugin`
class DemoPlugin extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<DemoPlugin> $type;

  @jni$_.internal
  DemoPlugin.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(r'com/demo/demo/DemoPlugin');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<DemoPlugin?> nullableType =
      $DemoPlugin$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<DemoPlugin> type = $DemoPlugin$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory DemoPlugin() {
    return DemoPlugin.fromReference(
      _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr).reference,
    );
  }

  static final _id_callback = _class.instanceMethodId(
    r'callback',
    r'()Ljava/lang/String;',
  );

  static final _callback =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun callback(): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString callback() {
    return _callback(
      reference.pointer,
      _id_callback as jni$_.JMethodIDPtr,
    ).object<jni$_.JString>(const jni$_.$JString$Type$());
  }
}

final class $DemoPlugin$NullableType$ extends jni$_.JType<DemoPlugin?> {
  @jni$_.internal
  const $DemoPlugin$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/demo/demo/DemoPlugin;';

  @jni$_.internal
  @core$_.override
  DemoPlugin? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : DemoPlugin.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<DemoPlugin?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DemoPlugin$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DemoPlugin$NullableType$) &&
        other is $DemoPlugin$NullableType$;
  }
}

final class $DemoPlugin$Type$ extends jni$_.JType<DemoPlugin> {
  @jni$_.internal
  const $DemoPlugin$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/demo/demo/DemoPlugin;';

  @jni$_.internal
  @core$_.override
  DemoPlugin fromReference(jni$_.JReference reference) =>
      DemoPlugin.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<DemoPlugin?> get nullableType =>
      const $DemoPlugin$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DemoPlugin$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DemoPlugin$Type$) &&
        other is $DemoPlugin$Type$;
  }
}
